/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-10-25 14:17:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel='stylesheet' type='text/css' href='css/lanren.css'/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"item_box box10\">\r\n");
      out.write("\t<div class=\"item_box_wp\">\r\n");
      out.write("\t\t<div class=\"voice_2\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"li1\" id=\"li1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">æäººä¹å®¶</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\" style=\"display:block\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img10.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>æäººä¹å®¶<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>ä½¿ç¨è¯­é³å¤å¼çæ¨¡å¼å°æå®çè¯­é³å¼å¥è³æ¥å¬äººï¼å¯éè¿è¿ç§æ¹å¼ä¸ºéå¯¹æ§çå®¢æ·æä¾ä¼è®®éç¥ãæ´»å¨éç¥ï¼å¹¶å¯éè¿APIæ¥å£ç¨åºåæ§å¶å¼åºæ¶é´ãå¼åºææåé¦</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"li2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">ç¹å»å¼å«</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img42.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>ç¹å»å¼å«<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>éè¿APPåºç¨åæé®ææµè§å¨ç½é¡µæé®ç¹å»å¹¶åèµ·IPéè¯ãè¿è¥åçº¿è·¯éè¯æå¡ï¼åå°ç¨æ·äº¤äºï¼æåç¨æ·ä½éª</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"li3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">ç´æ¨éè¯</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img49.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>ç´æ¨éè¯<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>æ è®ºæ¯æºè½ç»ç«¯ãæµè§å¨æ¨¡å¼ï¼éè¿APPæèç½é¡µåèµ·éè¯ï¼æ¥éæ¹ä¸ºææºç¨æ·æåºè¯ç¨æ·ï¼å¸¸è§éæè³ä¸ä¼ä¸æå¡ç¸å³çç§»å¨åºç¨ãä¼ä¸å®¢æåº§å¸­ã</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"li4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">åæ¨éè¯</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img50.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>åæ¨éè¯<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>åæ¶éè¿å¹³å°æ¹åèµ·ä¸»å«åè¢«å«åæ¹ï¼å®å¶éè¯æ¹æ»¡è¶³ä¸åéæ±çå®¢æ·æå¡ï¼ä¼ä¸æå¡æå¯æ ¹æ®å·ä½ä¸å¡éæ±ä¸ºå®¢æ·æä¾å®å¶æå¡</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"li5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">äºèç½éè¯</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img51.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>äºèç½éè¯<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>åºäºäºèç½çº¯ç½ç»éè¯ï¼æ è¿è¥ååå°åéå¶ï¼æ¥ææ´æ¸æ°çè¯­é³è´¨éï¼æ¯æè¯­é³ä¸æ¹å¯é¥çå å¯ä¼ è¾</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"li6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fold\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"img\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"txt\">è¯­é³ä¼è®®</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"unfold\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt><img src=\"images/img52.png\" /></dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>è¯­é³ä¼è®®<a href=\"#\">æ¥çæ¥å£ææ¡£>></a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>åæ¶æ¡¥æ¥å¤äººåºäºIPãçµè¯è¯­é³çä¼è®®æå¡ï¼åºäºAPIæ§å¶ä¼è®®æ¶é¿ãæåéè¯·ãç¦é³ãç§»é¤ç­åè½ã</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>         \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"src=\"js/lanren.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
