/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-10-25 14:29:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fpage_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zh\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"> \r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<span style=\"display:none;\">\r\n");
      out.write("</span><!-- ä»£ç é¨åbegin -->\r\n");
      out.write("<section class=\"strips\">\r\n");
      out.write("  <article class=\"strips__strip\">\r\n");
      out.write("\t<div class=\"strip__content\">\r\n");
      out.write("\t  <h1 class=\"strip__title\" data-name=\"Lorem\">Awesome</h1>\r\n");
      out.write("\t  \t <div class=\"strip__inner-text\">\r\n");
      out.write("\t  \t<p>hello! Welcome to lanrenzhijia!</p>\r\n");
      out.write("\t  \t<p><a href=\"#\" target=\"_blank\"></a></p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t  <a href=\"#\" target=\"_blank\"><i class=\"fa fa-qq\"></i></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <article class=\"strips__strip\">\r\n");
      out.write("\t<div class=\"strip__content\">\r\n");
      out.write("\t  <h1 class=\"strip__title\" data-name=\"Ipsum\">Words</h1>\r\n");
      out.write("\t  <div class=\"strip__inner-text\">\r\n");
      out.write("\t\t<h2>Ettrics</h2>\r\n");
      out.write("\t\t<p>éç¨æµè§å¨ï¼360ãFireFoxãChromeãSafariãOperaãå²æ¸¸ãæçãä¸çä¹çª. ä¸æ¯æIE8åä»¥ä¸æµè§å¨ã</p>\r\n");
      out.write("\t\t<p><a href=\"#\" target=\"_blank\"></a></p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t  <a href=\"#\" target=\"_blank\"><i class=\"fa fa-qq\"></i></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <article class=\"strips__strip\">\r\n");
      out.write("\t<div class=\"strip__content\">\r\n");
      out.write("\t  <h1 class=\"strip__title\" data-name=\"Dolor\">Go</h1>\r\n");
      out.write("\t  <div class=\"strip__inner-text\">\r\n");
      out.write("\t\t<h2>Ettrics</h2>\r\n");
      out.write("\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia sapiente deserunt consectetur, quod reiciendis corrupti quo ea aliquid! Repellendus numquam quo, voluptate. Suscipit soluta omnis quibusdam facilis, illo voluptates odit!</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t  <a href=\"#\" target=\"_blank\"><i class=\"fa fa-weibo\"></i></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <article class=\"strips__strip\">\r\n");
      out.write("\t<div class=\"strip__content\">\r\n");
      out.write("\t  <h1 class=\"strip__title\" data-name=\"Sit\">Inside</h1>\r\n");
      out.write("\t  <div class=\"strip__inner-text\">\r\n");
      out.write("\t\t<h2>Ettrics</h2>\r\n");
      out.write("\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia sapiente deserunt consectetur, quod reiciendis corrupti quo ea aliquid! Repellendus numquam quo, voluptate. Suscipit soluta omnis quibusdam facilis, illo voluptates odit!</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t  <a href=\"#\" target=\"_blank\"><i class=\"fa fa-weixin\"></i></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <article class=\"strips__strip\">\r\n");
      out.write("\t<div class=\"strip__content\">\r\n");
      out.write("\t  <h1 class=\"strip__title\" data-name=\"Amet\">Here</h1>\r\n");
      out.write("\t  <div class=\"strip__inner-text\">\r\n");
      out.write("\t\t<h2>Ettrics</h2>\r\n");
      out.write("\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia sapiente deserunt consectetur, quod reiciendis corrupti quo ea aliquid! Repellendus numquam quo, voluptate. Suscipit soluta omnis quibusdam facilis, illo voluptates odit!</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t  <a href=\"#\" target=\"_blank\"><i class=\"fa fa-leaf\"></i></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <i class=\"fa fa-close strip__close\"></i>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var Expand = function () {\r\n");
      out.write("\tvar tile = $('.strips__strip');\r\n");
      out.write("\tvar tileLink = $('.strips__strip > .strip__content');\r\n");
      out.write("\tvar tileText = tileLink.find('.strip__inner-text');\r\n");
      out.write("\tvar stripClose = $('.strip__close');\r\n");
      out.write("\tvar expanded = false;\r\n");
      out.write("\tvar open = function () {\r\n");
      out.write("\t\tvar tile = $(this).parent();\r\n");
      out.write("\t\tif (!expanded) {\r\n");
      out.write("\t\t\ttile.addClass('strips__strip--expanded');\r\n");
      out.write("\t\t\ttileText.css('transition', 'all .6s 1s cubic-bezier(0.23, 1, 0.32, 1)');\r\n");
      out.write("\t\t\tstripClose.addClass('strip__close--show');\r\n");
      out.write("\t\t\tstripClose.css('transition', 'all .6s 1s cubic-bezier(0.23, 1, 0.32, 1)');\r\n");
      out.write("\t\t\texpanded = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tvar close = function () {\r\n");
      out.write("\t\tif (expanded) {\r\n");
      out.write("\t\t\ttile.removeClass('strips__strip--expanded');\r\n");
      out.write("\t\t\ttileText.css('transition', 'all 0.15s 0 cubic-bezier(0.23, 1, 0.32, 1)');\r\n");
      out.write("\t\t\tstripClose.removeClass('strip__close--show');\r\n");
      out.write("\t\t\tstripClose.css('transition', 'all 0.2s 0s cubic-bezier(0.23, 1, 0.32, 1)');\r\n");
      out.write("\t\t\texpanded = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tvar bindActions = function () {\r\n");
      out.write("\t\ttileLink.on('click', open);\r\n");
      out.write("\t\tstripClose.on('click', close);\r\n");
      out.write("\t};\r\n");
      out.write("\tvar init = function () {\r\n");
      out.write("\t\tbindActions();\r\n");
      out.write("\t};\r\n");
      out.write("\treturn { init: init };\r\n");
      out.write("}();\r\n");
      out.write("Expand.init();\r\n");
      out.write("</script>\r\n");
      out.write("<!-- ä»£ç é¨åend -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
