/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-12-18 01:07:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Expand, contract, animate forms with jQuery wihtout leaving the page\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"expand, form, css3, jquery, animate, width, height, adapt, unobtrusive javascript\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/login/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/login/cufon-yui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/login/ChunkFive_400.font.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tCufon.replace('h1',{ textShadow: '1px 1px #fff'});\r\n");
      out.write("\t\t\tCufon.replace('h2',{ textShadow: '1px 1px #fff'});\r\n");
      out.write("\t\t\tCufon.replace('h3',{ textShadow: '1px 1px #000'});\r\n");
      out.write("\t\t\tCufon.replace('.back');\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script language=\"javascript\" src=\"js/jquery.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/jquery.form.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/comman.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/login/event.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<h1>DIANO</h1>\r\n");
      out.write("\t<h2>\r\n");
      out.write("\t\tWelcome to <span>DIANO</span>\r\n");
      out.write("\t</h2>\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div id=\"form_wrapper\" class=\"form_wrapper\">\r\n");
      out.write("\t\t\t<form class=\"register\", id=\"register_body\">\r\n");
      out.write("\t\t\t\t<h3>Register</h3>\r\n");
      out.write("\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>First Name:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"First Name\" id='reg_fn' onblur=\"checkfn()\"/> <span class=\"error\" id=\"reg_fnerror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>Last Name:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Last Name\" id='reg_ln' onblur=\"checkln()\"/> <span class=\"error\" id=\"reg_lnerror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>Email:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Email\" id='reg_email' onblur=\"checkEmail()\"/> <span class=\"error\" id=\"reg_emailerror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"column\">-->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>Username:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Username\" id='reg_usn' onblur=\"checkUser()\"/> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\" id=\"reg_usnerror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>Password:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" id='reg_pw' onblur=\"checkPwd()\"/> <span class=\"error\" id=\"reg_pwerror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!--<label>Re-enter password:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" value=\"http://\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error\">This is an error</span>-->\r\n");
      out.write("\t\t\t\t\t\t<label>Re-enter password:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" placeholder=\"Re-enter password\" id='reg_pwcf' onblur=\"checkpwd_cf()\"/> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"error\" id=\"reg_pwcferror\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t\t\t<div class=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" /> <span>Send me updates</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Register\" id=\"regBtn\" /> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"index.html\" rel=\"login\" class=\"linkform\">You have an\r\n");
      out.write("\t\t\t\t\t\taccount already? Log in here</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form class=\"login active\">\r\n");
      out.write("\t\t\t\t<h3>Login</h3>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label>Username:</label> <input type=\"text\" id=\"idInput\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label>Password: <a href=\"forgot_password.jsp\"\r\n");
      out.write("\t\t\t\t\t\trel=\"forgot_password\" class=\"forgot linkform\">Forgot your\r\n");
      out.write("\t\t\t\t\t\t\tpassword?</a></label> <input type=\"password\" id=\"pwInput\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t\t\t<div class=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"rememberBox\" /><span>Keep me\r\n");
      out.write("\t\t\t\t\t\t\tlogged in</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Login\" id=\"subBtn\"></input> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"register.jsp\" rel=\"register\" class=\"linkform\">You don't\r\n");
      out.write("\t\t\t\t\t\thave an account yet? Register here</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form class=\"forgot_password\">\r\n");
      out.write("\t\t\t\t<h3>Forgot Password</h3>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label>Username or Email:</label> <input type=\"text\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"error\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Send reminder\"></input> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"index.html\" rel=\"login\" class=\"linkform\">Suddenly\r\n");
      out.write("\t\t\t\t\t\tremebered? Log in here</a> <a href=\"register.html\" rel=\"register\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"linkform\">You don't have an account? Register here</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a class=\"back\" href=\"#\">back to main page</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- The JavaScript -->\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t//the form wrapper (includes all forms)\r\n");
      out.write("\t\t\t\tvar $form_wrapper\t= $('#form_wrapper'),\r\n");
      out.write("\t\t\t\t\t//the current form is the one with class active\r\n");
      out.write("\t\t\t\t\t$currentForm\t= $form_wrapper.children('form.active'),\r\n");
      out.write("\t\t\t\t\t//the change form links\r\n");
      out.write("\t\t\t\t\t$linkform\t\t= $form_wrapper.find('.linkform');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t//get width and height of each form and store them for later\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$form_wrapper.children('form').each(function(i){\r\n");
      out.write("\t\t\t\t\tvar $theForm\t= $(this);\r\n");
      out.write("\t\t\t\t\t//solve the inline display none problem when using fadeIn fadeOut\r\n");
      out.write("\t\t\t\t\tif(!$theForm.hasClass('active'))\r\n");
      out.write("\t\t\t\t\t\t$theForm.hide();\r\n");
      out.write("\t\t\t\t\t$theForm.data({\r\n");
      out.write("\t\t\t\t\t\twidth\t: $theForm.width(),\r\n");
      out.write("\t\t\t\t\t\theight\t: $theForm.height()\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//set width and height of wrapper (same of current form)\r\n");
      out.write("\t\t\t\tsetWrapperWidth();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tclicking a link (change form event) in the form\r\n");
      out.write("\t\t\t\tmakes the current form hide.\r\n");
      out.write("\t\t\t\tThe wrapper animates its width and height to the \r\n");
      out.write("\t\t\t\twidth and height of the new current form.\r\n");
      out.write("\t\t\t\tAfter the animation, the new form is shown\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t$linkform.bind('click',function(e){\r\n");
      out.write("\t\t\t\t\tvar $link\t= $(this);\r\n");
      out.write("\t\t\t\t\tvar target\t= $link.attr('rel');\r\n");
      out.write("\t\t\t\t\t$currentForm.fadeOut(400,function(){\r\n");
      out.write("\t\t\t\t\t\t//remove class active from current form\r\n");
      out.write("\t\t\t\t\t\t$currentForm.removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t//new current form\r\n");
      out.write("\t\t\t\t\t\t$currentForm= $form_wrapper.children('form.'+target);\r\n");
      out.write("\t\t\t\t\t\t//animate the wrapper\r\n");
      out.write("\t\t\t\t\t\t$form_wrapper.stop()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t .animate({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth\t: $currentForm.data('width') + 'px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\theight\t: $currentForm.data('height') + 'px'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t },500,function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//new form gets class active\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$currentForm.addClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//show the new form\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$currentForm.fadeIn(400);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction setWrapperWidth(){\r\n");
      out.write("\t\t\t\t\t$form_wrapper.css({\r\n");
      out.write("\t\t\t\t\t\twidth\t: $currentForm.data('width') + 'px',\r\n");
      out.write("\t\t\t\t\t\theight\t: $currentForm.data('height') + 'px'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\tfor the demo we disabled the submit buttons\r\n");
      out.write("\t\t\t\tif you submit the form, you need to check the \r\n");
      out.write("\t\t\t\twhich form was submited, and give the class active \r\n");
      out.write("\t\t\t\tto the form you want to show\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t$form_wrapper.find('input[type=\"submit\"]')\r\n");
      out.write("\t\t\t\t\t\t\t .click(function(e){\r\n");
      out.write("\t\t\t\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t });\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction checkstr(str,digit){\r\n");
      out.write("\t\t\t\t\tvar n = 0;\r\n");
      out.write("\t\t\t\t\tfor(i = 0; i < str.length; i++){\r\n");
      out.write("\t\t\t\t\t\tvar leg = str.charCodeAt(i);\r\n");
      out.write("\t\t\t\t\t\tif(leg > 255){\r\n");
      out.write("\t\t\t\t\t\t\tn += 2;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tn += 1;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(n > digit){\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//check repeat\r\n");
      out.write("\t\t\t\tfunction checkpwd_cf(){\r\n");
      out.write("\t\t\t\t\tvar pwd_cfError = document.getElementById(\"reg_pwcferror\");\r\n");
      out.write("\t\t\t\t\tvar pwd = $('#reg_pw').val();\r\n");
      out.write("\t\t\t\t\tvar pwd_cf = $('#reg_pwcf').val();\r\n");
      out.write("\t\t\t\t\tif(pwd!=pwd_cf){\r\n");
      out.write("\t\t\t\t\t\tpwd_cfError.innerHTML=\"The passwords you entered do not match.\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tpwd_cfError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//The passwords you entered do not match.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction checkUser(){\r\n");
      out.write("\t\t\t\t\t//Username entered already in use. Please choose a different name.\r\n");
      out.write("\t\t\t\t\tvar user = $('#reg_usn').val();\r\n");
      out.write("\t\t\t\t\tvar userError = document.getElementById(\"reg_usnerror\");\r\n");
      out.write("\t\t\t\t\tif(user.length >= 4 && user.length <= 16){\r\n");
      out.write("\t\t\t\t\t\tuserError.innerHTML = \"\"\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tuserError.innerHTML = \"\"\r\n");
      out.write("\t\t\t\t\t\tuserError.innerHTML = \"the length: 4 - 16\"\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction checkPwd(){\r\n");
      out.write("\t\t\t\t\tvar Expression = /^[A-Za-z]{1}([A-Za-z0-9]|[._]){5,29}$/;\r\n");
      out.write("\t\t\t\t\tvar objExp = new RegExp(Expression); //Create exp obj\r\n");
      out.write("\t\t\t\t\tvar pwdError = document.getElementById(\"reg_pwerror\");\r\n");
      out.write("\t\t\t\t\tvar pwd = $('#reg_pw').val();\r\n");
      out.write("\t\t\t\t\tif(pwd.length<6||pwd.length>16){\r\n");
      out.write("\t\t\t\t\t\tpwdError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\tpwdError.innerHTML=\"the langth of pw: 6 - 16!\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(objExp.test(pwd) == false){//exp ok\r\n");
      out.write("\t\t\t\t\t\tpwdError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\tpwdError.innerHTML=\"your password cannot include /'// &*()\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tpwdError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction checkEmail(){\r\n");
      out.write("\t\t\t\t\tvar str = $('#reg_email');\r\n");
      out.write("\t\t\t\t\tvar emailError = document.getElementById(\"reg_emailerror\");\r\n");
      out.write("\t\t\t\t\tvar error = \"please entry the correct email address.\";\r\n");
      out.write("\t\t\t\t\t//exp starting by '/'\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar Expression=/\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*/;\r\n");
      out.write("\t\t\t\t\tvar objExp=new RegExp(Expression);\r\n");
      out.write("\t\t\t\t\tif(objExp.test(str)==true){\r\n");
      out.write("\t\t\t\t\t\temailError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\temailError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\temailError.innerHTML=error;\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction checkfn(){\r\n");
      out.write("\t\t\t\t\tvar fnError = document.getElementById(\"reg_fnerror\");\r\n");
      out.write("\t\t\t\t\tvar fn = $.trim($(\"#reg_fn\").val());\r\n");
      out.write("\t\t\t\t\tif(fn.length > 0){\r\n");
      out.write("\t\t\t\t\t\tfnError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tfnError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\tfnError.innerHTML=\"please entry your first name\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfunction checkln(){\r\n");
      out.write("\t\t\t\t\tvar lnError = document.getElementById(\"reg_lnerror\");\r\n");
      out.write("\t\t\t\t\tvar ln = $.trim($(\"#reg_ln\").val());\r\n");
      out.write("\t\t\t\t\tif(ln.length > 0){\r\n");
      out.write("\t\t\t\t\t\tlnError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlnError.innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\tlnError.innerHTML=\"please entry your last name\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
