/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0
 * Generated at: 2017-12-17 04:50:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"> \r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"api/bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"css/index-landing-page.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/mainpage.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/searchbar.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/jquery.form.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/comman.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"api/bootstrap/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".nav-link-mei{color:#868e96;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\" >\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">★종합설계프로젝트2 APPLUS★ </a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" >\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\" >\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link-mei\" href=\"index.html\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_aboutus\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link-mei\" href=\"login.jsp\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_login\">Log in</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link-mei\" href=\"Account.jsp\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_accountInfo\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link-mei\" href=\"javascript:;\" onclick=\"onUploadBtn()\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_fileup\">upload</a></li> \r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link-mei\" href=\"javascript:;\" onclick=\"logout()\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_logout\">Log out</a></li> \r\n");
      out.write("\t\t\t\t\t<!-- <li class=\"nav-item\"><a class=\"nav-link\" href=\"accountSignin.jsp\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn_signin\">Sign in</a></li>\r\n");
      out.write("\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"search-wrapper\">\r\n");
      out.write("\t<div id=\"search\" class=\"cd-main-search\">\r\n");
      out.write("\t\t<form onsubmit=\"submitFn(this, event);\">\r\n");
      out.write("\t\t\t<div class=\"search-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"input-holder\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"search-input\" placeholder=\"Type to search\" />\r\n");
      out.write("\t\t\t\t\t<button class=\"search-icon\" onclick=\"searchToggle(this, event);\"><span></span></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<span class=\"close\" onclick=\"searchToggle(this, event);\"></span>\r\n");
      out.write("\t\t\t<div class=\"result-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t<a>asd</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tif(checkCookie()){\r\n");
      out.write("\t\tdocument.getElementById(\"btn_login\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"btn_accountInfo\").style.display=\"block\";\r\n");
      out.write("\t\t$(\"#btn_logout\").show();\r\n");
      out.write("\t\t$(\"#btn_fileup\").show();\r\n");
      out.write("\t\tdocument.getElementById(\"btn_accountInfo\").innerHTML = getCookie('username');\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$(\"#btn_login\").show(100);\r\n");
      out.write("\t\t$(\"#btn_accountInfo\").hide(100);\r\n");
      out.write("\t\t$(\"#btn_logout\").hide();\r\n");
      out.write("\t\t$(\"#btn_fileup\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction searchToggle(obj, evt){\r\n");
      out.write("\t\tvar container = $(obj).closest('.search-wrapper');\r\n");
      out.write("\r\n");
      out.write("\t\tif(!container.hasClass('active')){\r\n");
      out.write("\t\t\t  container.addClass('active');\r\n");
      out.write("\t\t\t  evt.preventDefault();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){\r\n");
      out.write("\t\t\t  container.removeClass('active');\r\n");
      out.write("\t\t\t  // clear input\r\n");
      out.write("\t\t\t  container.find('.search-input').val('');\r\n");
      out.write("\t\t\t  // clear and hide result container when we press close\r\n");
      out.write("\t\t\t  container.find('.result-container').fadeOut(100, function(){$(this).empty();});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction submitFn(obj, evt){\r\n");
      out.write("\t\tvalue = $(obj).find('.search-input').val().trim();\r\n");
      out.write("\r\n");
      out.write("\t\t_html = \"Yup yup! Your search text sounds like this: \";\r\n");
      out.write("\t\tif(!value.length){\r\n");
      out.write("\t\t\t_html = \"Yup yup! Add some text friend :D\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t_html += \"<b>\" + value + \"</b>\";\r\n");
      out.write("\t\t\tvar url = \"tabletest.jsp?keyword=\"+ value;\r\n");
      out.write("\t\t\twindow.location.href=url;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(obj).find('.result-container').html('<span>' + _html + '</span>');\r\n");
      out.write("\t\t$(obj).find('.result-container').fadeIn(100);\r\n");
      out.write("\r\n");
      out.write("\t\tevt.preventDefault();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout(){\r\n");
      out.write("\t\tdelCookie(\"username\");\r\n");
      out.write("\t\ttop.location = \"main.jsp\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
